DROP TABLE IF EXISTS DELAY_JOB;


##############################################

CREATE TABLE DELAY_JOB
(
  ID               VARBINARY(32) NOT NULL,
  VERSION          NUMERIC(8)    NOT NULL DEFAULT 1,
  SRC_CONTEXT      VARCHAR(32)   NOT NULL,
  SRC_OBJ_ID       VARCHAR(32)   NOT NULL,
  TOPIC            VARCHAR(32)   NOT NULL,
  STATUS           NUMERIC(2)    NOT NULL,
  EXPIRES          LONG          NOT NULL,
  CREATED_AT       LONG          NOT NULL,
  LAST_MODIFIED_AT LONG          NOT NULL,
  CONSTRAINT PK_DELAY_JOB PRIMARY KEY (ID)
);