language: java

jdk:
  - oraclejdk8

env:
  global:
     # OSS_NEXUS_USER
     - secure: "vJpCZWVzu36MXVWq8Noiiv8IdCjn0IA4tyL0bPgVa5SiqdvkHpGWiVYfMeKcy9arjvFYOHy2qtVAyvxs/Pfv6Q6SQ1t8u91r1Y9BHpOrvRC4pAiemOyyD3SFUSvIEy1BfP6kWddlSok89DGcJJ76A2w+RC00NjVW+Zj0lSUYM4xczuz39WSmC8raOZLR/FdrcC3Ltgx1fR+fRVOk0P8k7cCqz7LWJewtj5UPyWiacvq5bZCQ3+w10EEdgthK8nadwEWCFk3vlt92Bwp3amWeP41ENcejt1pQJBeiAgzfz/C5Urv0KZzGApfsQOKuqqpRHFJOsmMvj+WFedGXHTpA4S2j/9SIlH17r3vrvFxrRaYdgPdjURV9leYSC9uHOkirBx87osv6XzwtFVFqtMp2ahSRbefP/ghlJt+FRXZLOff8UbnHAQv6xrk6pt9g566LR5HSaredjAUDjVBRNd61pfsKGtzTSZ6qA45LS+LKz6svxPKjD1w7w6RhB7GyqHXBAsVAYt6u1/JUI6p59TXOWja+Z9WJA8dv79JMXdNmvadlLoTV3tHljQokcsbXCzUrRjDcoRVJbqVNB5Y9BoexpoZqj9SZ4PBAbtBCVvUaMgWq2v67vjj62Zv4ZRzz+mMb0V7ynclOHCSgvjNipSb380P96LOyt0icFE7RZ8+1FpU="
     # OSS_NEXUS_PASS
     - secure: "tx3LSBm+R93LN8rKMs2UQw/oP2kNlRKlNJzN60wrs0QReCjwjHlaDeMmeO6vpk2MuSTlqI57KpbGihm7LKlbHwF8j+Vi+GM3mmBn0AOLrbNnPpZTGO0L0DIDe1RIdT/h+B47C1Z+kZzBJ6t1GYJczghF2YrZy0Yw35MlbY4tP9ZGmRQxhkcIkifTFU2+cT9IJZ4BrAdSJomeMQluRMuPEizfIUApETAUmY4QmMtjtRV0LkNnuOw+GmYdNY9xkViY/DQrKfGO8X3ebv1RgFXaiLPz0gOlvKHxr4my7V4s4ZbsT4gxzwoW1/odJSKmKW10vBcsm6dYCLclgHJaY4Qt0AKBSB1HkByswASYZeJNO8roRzWvQI0aZ3o/ktxRrKXr8Nk2tcwiDNpjj1Ec0IrN8R4hmdAozEmQuZZixuWRU9baHJvIeqDlb8KDFP2qxEW42RiS42Ym0w/1E24f6eze7QBLIuHaPsZJFQWUYZSfqlulw4zZXU9CLX/wuWDOrBCcPVkT3jzYhZowWMrCt9nXhTwDn4LWTrcZFt+m11RBLF69trg7VffQvLtl95JO8SZz1ONHdrISQa/q5a26r/lumKYhttHDMfYHZPk9c+cE6wNkoEjrGu2bGELGbFrVal9K1fwDxn90YMeSx27o/wHvXcXrbq/sHsZd1D8bk1nt1Lo="

     # BINTRAY_USER
     - secure: "WagSHjnV4t4hbSOobF4qiL4z46Iih8tjHOTx26rKmj6Pc8psvYTefGPrDlUq33TKIb5w1RmSvSmPtYNazPhklEC93Bp5SaM9TdHC4fnS/qlFS+Nmdv+ujjQEM6ouKXZT4YQJRiRUUVrzu0wjdAYGWgO12BDuVxkkTsA/KLtlcSrOAHk0f5wfictFdKG43LxqFwS/X0oz9JAxwlwoBGTSGamdEYc1M9thRowDlR/mffny7Obly4GBqXmUp234tlVmp8SODk69edaQ6af6HYP8VB67lJy9Dubpzhfgwx02p8kK3cRkgh4HcqDWzVw/hJ1H6OKv7cZIxcv1HL2wkWNOuB1+SSswmcVJhO9w7xN+7xyu22/5PR1IlxYthkeww8RB2z1Jkiu6sFINgJzq5TP4EVTa8O72Bk3Kw6hHBEes3XmiMbZLX/Eg8iPuTuyNjw+X+ypa2pBXKEd2vhRgVervhdlnwTGjZkVyQlgElXQBYkFl/Qj7Nly0k2P5iNn90LUIQc90Bh0xQ/EBmE8hsirCN7p1h5zd9fxJ/R8CMUa3UjL6lIfOyJ+ebrL3IjWJL6HGHxsRxr2pWs4DQagIPml9CiQTNWje3LFgbLncfNDAs2+cBM82/CK0rNrvo1gn9uJrIOULHU3Hx2eiXbgsEO5k5tiWLr8aUNVw8ooARuVr54A="
     # BINTRAY_KEY
     - secure: "ewrbFN4gSkXgX4jTwmUyXO1vTS9/qwi5smWkjlF3GbFCSwPIMX4kmeOggzPDJQKLvqbcuxAaDQjvtHF8oTV/YygqAKSeQ3hCthoEYdN4mLjNMf03atOlkH7TsRbYjhqVyUmKCFMkZoqxQN/ev7NDCZ+K6X1HSWtZfAwJdEY2pF8TDoxrzONOgXIHlUkNuFPxa+O9jOsfdP/8UmS7HxpozoeRzhgw2L8uz5snVHrfxHaIJ/1AESbA9NdVQhSCvRq+ZA0tIT348c3R7+viXKblVVOXPojuzIWpnhsEwoTHI3zLiT+XxqUCTGTjvbX5RjUYsgtVl7qUcSFnmJZ723yrSHIVSn4kyk1+9IFszzvA/zk5BjoUQN+Q0E6QLfE9R3EhiENApeRR/axaKnJV+r7DSg0eFr6BxPHgrjCZpxFHT5fYfu5aF3kKRncJAe0GwM+hSEjZTxa+ciMOSe8+uR8ZrluR5oidiVYA5dqCy6/bhoVEyURvX30BoawSTrXLSv7K6JJJLenZxK9aRtSqYt2j7upnRoq94RntbdNOfyj4KpaMN/+USkNEycoSD6b2oBo2iwYqGZOsk7wsa0y2PYLVEbaSmdskeOtvh/t5JQC26UYOMPmqRpjoqTBs2teohI3UUPF7dwTt55qYWC+onqT21ikBDbFfPZKQYtL0xDs3sI0="

install: ./gradlew clean
before_script:
  - ./go.sh docker
script: ./gradlew test

deploy:
  - provider: script
    script: ./gradlew publish
    on:
      tags: false
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true

cache:
  directories:
    - ~/.gradle/
